name: Lint

on:
  push:
    branches:
      - main

jobs:
  lint: 
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with: 
          node-version: 16
      
      - name: Install pnpm
        run: npm i -g pnpm
      
      - name: Install Dependencies
        run: pnpm install
      
      - name: ESLint
        run: pnpm run eslint
  
  typecheck: 
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with: 
          node-version: 16
      
      - name: Install pnpm
        run: npm i -g pnpm
      
      - name: Install Dependencies
        run: pnpm install
      
      - name: Typecheck
        run: pnpm run typecheck