name: Test

on:
  push:
    branches:
      - main

jobs:
  lint: 
    name: Jest Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with: 
          node-version: 16
      
      - name: Install pnpm
        run: npm i -g pnpm
      
      - name: Install Dependencies
        run: pnpm install
      
      - name: Jest
        run: pnpm run test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./reports/coverage-final.json
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}